#!/usr/bin/env bash

set -eu

PR_ASSIGNEE="wangzhihao0629"
DB_CLUSTER_IDENTIFIER="infra-cloud-testing-pg-upgrade-test-cluster"
NEW_DB_CLUSTER_IDENTIFIER="infra-cloud-testing-pg-upgrade-test-cluster-v152"

generate_pr_assignment_post_data() {
  cat << EOF
{
  "assignees":["$PR_ASSIGNEE"]
}
EOF
}

generate_pr_description() {
  cat << EOF
## Description

As the preparation of blue/green upgrade of [$DB_CLUSTER_IDENTIFIER](https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#database:id=$DB_CLUSTER_IDENTIFIER;is-cluster=true) to $TARGET_VERSION, we need to set up the replication cluster $NEW_DB_CLUSTER_IDENTIFIER to replicate from $DB_CLUSTER_IDENTIFIER so that we can perform the DNS switch over later.

When you see this pull request

- The replication cluster [$NEW_DB_CLUSTER_IDENTIFIER](https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#database:id=$NEW_DB_CLUSTER_IDENTIFIER;is-cluster=true) should have already been set up and you should be able to see it on [AWS console](https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#databases:)
- The resources that are just created (RDS cluster, parameter groups, etc) should have already been imported to Terraform, which means the \`atlantis plan\` output should not indicate that it will create these new resources.

If you have any questions, please reach out to [#proj-automated-rds-upgrade](https://duolingo.slack.com/archives/C055VNXUQ2X) or [#opslevel-check-postgresql-upgrade](https://duolingo.slack.com/archives/C058FUXEVE2) if this is related to 2023 Q3 OpsLevel check.

## Verification Steps
- [ ] Check \`altantis plan\` and verify the output
- [ ] Modify the \`rds.tf\` if needed

> This pull request is autogenerated by https://jenkins-ci.duolingo.com/job/setup-pg-logical-replication-cluster/

EOF
}

pr_number="$(
curl -L \
	-X POST \
	-H "Accept: application/vnd.github+json" \
	-H "Authorization: Bearer ${GITHUB_TOKEN}" \
	-H "X-GitHub-Api-Version: 2022-11-28" \
	https://api.github.com/repos/wangzhihao0629/wangzhihao0629/pulls \
	--data "$(generate_pr_creation_post_data)" | jq -r '.number'
)"
echo "pr_number=$pr_number"
pr_assignment_api_response="$(
curl -L \
	-X POST \
	-H "Accept: application/vnd.github+json" \
	-H "Authorization: Bearer ${GITHUB_TOKEN}" \
	-H "X-GitHub-Api-Version: 2022-11-28" \
	https://api.github.com/repos/wangzhihao0629/wangzhihao0629/issues/${pr_number}/assignees \
	--data "$(generate_pr_assignment_post_data)"
)"